# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.sample_parameters_cpp <- function(p, p0 = 0.5, alpha = -1, beta = -1, a = 0.5, b = 0.5, num_sample = 100000L, seed = 1L) {
    .Call(`_braggR_sample_parameters_cpp`, p, p0, alpha, beta, a, b, num_sample, seed)
}

